name: Clang

on:
  push:
  @@ -7,16 +7,16 @@ on:
  pull_request:
    paths-ignore:
      - 'sql/**'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -yq libboost-all-dev clang-14 libace-dev
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 100 
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-14 100
    - name: Setup
      run: |
        mkdir bin